#!/bin/bash

TARGETDIR=$1
RAWPATH=$2
ANALYSISPATH=$3

NICE="nice -n 19"

FONTSIZE=9
PICXSIZE="480"
PICYSIZE="320"

OWNSTROKESCOLOR=1
OWNEVENTSCOLOR=2
STROKESCOLOR=3


if [ x$TARGETDIR == x ] ; then
  TARGETDIR="."
fi

if [ x$RAWPATH == x ]; then
  RAWPATH="/var/cache/blitzortung/raw"
fi

if [ x$ANALYSISPATH == x ]; then
  ANALYSISPATH="/var/cache/blitzortung/analysis"
fi

TMPDATA=$(mktemp /tmp/$(basename $0).XXXXXX)
STARTTIME=$(date +"%Y-%m-%d %H:%M:00" -d -1day)
ENDTIME=$(date +"%Y-%m-%d %H:%M:00")

$NICE blitzortung-statistics --mode=histogram --time-delta=15 --data-path=$RAWPATH > $TMPDATA

$NICE gnuplot <<***
set term png $FONTSIZE size $PICXSIZE,$PICYSIZE
set output "$TARGETDIR/timecount.png"
set xdata time
set timefmt "%Y-%m-%d %H:%M:%S"
set xlabel "UTC time"
set ylabel "# of measured local events"
set boxwidth 15*60
set log y
set xr ["$STARTTIME":"$ENDTIME"]
set yr [0.75:*]
set grid front
set format x "%H:%M"
plot 1 lt -2 not, "$TMPDATA" u 1:3 not w boxes lt $OWNEVENTSCOLOR fs solid 0.5
***

$NICE gnuplot <<***
set term png $FONTSIZE size $PICXSIZE,$PICYSIZE
set output "$TARGETDIR/timeamp.png"
set xdata time
set timefmt "%Y-%m-%d %H:%M:%S"
set xlabel "UTC time"
set ylabel "average amplitude of local events"
set boxwidth 15*60
set grid front
set xr ["$STARTTIME":"$ENDTIME"]
set yr [0:*]
set format x "%H:%M"
set pointsize 0.8
plot 0.2 lt -2 not, "$TMPDATA" u 1:4 not w p lt $OWNEVENTSCOLOR
***

$NICE blitzortung-statistics --mode=data --time-delta=120 --data-path=$RAWPATH > $TMPDATA

TOTALSAMPLES=$(wc -l $TMPDATA | cut -d" " -f1)

$NICE gnuplot <<***
set term png $FONTSIZE size $PICYSIZE,$PICYSIZE
set output "$TARGETDIR/xyamp.png"
set size square
set title "last 2 hours events (sum $TOTALSAMPLES)"
set xlabel "x amplitude"
set ylabel "y amplitude"
set xr [-1.0:1.0]
set yr [-1.0:1.0]
set grid front
plot "$TMPDATA" u 8:9 not w p lt $OWNEVENTSCOLOR
***

$NICE blitzortung-statistics --mode=strokes --time-delta=5 --data-path=$RAWPATH > $TMPDATA

STARTTIME=$(date +"%Y-%m-%d %H:%M:00" -d -115minutes)

TOTALSTROKES=$(cat $TMPDATA | awk 'BEGIN {sum=0} {sum += $3} END {print sum}')
TOTALPARTICIPATEDSTROKES=$(cat $TMPDATA | awk 'BEGIN {sum=0} {sum += $4} END {print sum}')
PARTICIPATEDPERCENT=$(echo $TOTALPARTICIPATEDSTROKES $TOTALSTROKES | awk '{printf "%.1f", 100.0*$1/$2}')

$NICE gnuplot <<***
set term png $FONTSIZE size $PICXSIZE,$PICYSIZE
set output "$TARGETDIR/strokes.png"
set xdata time
set timefmt "%Y-%m-%d %H:%M:%S"
set xlabel "UTC time"
set ylabel "# of strokes"
set boxwidth 5*60
set log y
set xr ["$STARTTIME":"$ENDTIME"]
set yr [0.75:*]
set xtics 15*60
set grid front
set format x "%H:%M"
plot 1 lt -2 not, "$TMPDATA" u 1:3 ti "total (sum $TOTALSTROKES)" w boxes lt $STROKESCOLOR fs solid 0.5, \
       "" u 1:4 ti "sensor participated (sum $TOTALPARTICIPATEDSTROKES, avg. $PARTICIPATEDPERCENT %)" w boxes lt $OWNSTROKESCOLOR fs solid 0.5
***

$NICE blitzortung-statistics --mode=radar --time-delta=120 --data-path=$RAWPATH > $TMPDATA

$NICE gnuplot <<***
set term png $FONTSIZE size $PICYSIZE,$PICYSIZE
set output "$TARGETDIR/radar.png"
set size square
set angles degree
set grid polar
set polar
set title "lightning radar (last 2 hours)"
plot 0 lt -2 not, "$TMPDATA" u (90-\$1):2 not w p lt $STROKESCOLOR
***

RESIDUAL_FILE=$ANALYSISPATH/residuals.txt
$NICE blitzortung-statistics --mode=residual --time-delta=15 --data-path=$RAWPATH >> $RESIDUAL_FILE

$NICE blitzortung-statistics --mode=residual --time-delta=120 --data-path=$RAWPATH > $TMPDATA

$NICE gnuplot <<***
bin(x, s) = s*floor(x/s+0.5)
binwidth = 5.0

set term png $FONTSIZE size $PICXSIZE,$PICYSIZE
set output "$TARGETDIR/residuals.png"
set title "last 2 hours residual times"
set xlabel "residual time [us]"
set ylabel "count"
set grid front
set boxwidth 5

plot 0 lt -2 not, "$TMPDATA" u (bin(\$3,binwidth)):(1) not smooth frequency w boxes lt $OWNSTROKESCOLOR fs solid 0.5
***

rm -rf $TMPDATA

STATISTICS_FILE=$ANALYSISPATH/statistics.txt

ACTUALSTROKEDATA=$($NICE blitzortung-statistics --mode=strokes | head -1)
ACTUALSTROKES=$(echo $ACTUALSTROKEDATA | cut -d" " -f3)
ACTUALPARTICIPATEDSTROKES=$(echo $ACTUALSTROKEDATA | cut -d" " -f4)
ACTUALSAMPLES=$($NICE blitzortung-statistics --mode=data | wc -l)

echo "$ENDTIME $ACTUALSTROKES $ACTUALPARTICIPATEDSTROKES $ACTUALSAMPLES" >> $STATISTICS_FILE

STARTTIME=$(date +"%Y-%m-%d %H:%M:00" -d -1week)
ENDTIME=$(date +"%Y-%m-%d %H:%M:00")

$NICE gnuplot <<***
set term png $FONTSIZE size $PICXSIZE,$PICYSIZE
set output "$TARGETDIR/statistics.png"
set title "participation statistics"
set xdata time
set timefmt "%Y-%m-%d %H:%M:%S"
set xlabel "UTC time"
set ylabel "counts per quarter hour"
set xr ["$STARTTIME":"$ENDTIME"]
set grid front
plot 0 lt -2 not, \
       "<tail -672 $STATISTICS_FILE" u 1:5 ti "local events" w l lt $OWNEVENTSCOLOR lw 2, \
       "" u 1:3 ti "strokes" w l lt $STROKESCOLOR lw 2, \
       "" u 1:4 ti "participated strokes" w l lt $OWNSTROKESCOLOR lw 2
***

