#!/usr/bin/python

import os, sys
import subprocess

import glob, re

import datetime

whitespace = re.compile('\s+')

def total_seconds(time):
  if isinstance(time, datetime.datetime):
    return time.hour * 3600 + time.minute * 60 + time.second
  else:
    return time.seconds


rawPath = '/var/cache/blitzortung/raw'

rawFileNames = glob.glob(os.path.join(rawPath, '*.bor'))

rawFileNames.sort()

rawFiles = {}

for rawFileName in rawFileNames:
  date = datetime.datetime.strptime(rawFileName[-12:-4], '%Y%m%d').date()
  if not rawFiles.has_key(date):
    rawFiles[date] = rawFileName
  else:
    print "ERROR: double date!"
    sys.exit(1)

if len(rawFiles) == 0:
  print "ERROR: no data files found in folder '%s'" % rawPath
  sys.exit(1)


# determine start time
now = datetime.datetime.utcnow()

offset = datetime.timedelta(minutes=15)

seconds = total_seconds(now)
seconds /= total_seconds(offset)
seconds *= total_seconds(offset)

hour = now.replace(hour = seconds/3600, minute= seconds / 60 % 60, second= seconds % 60, microsecond=0)

hour -= datetime.timedelta(days=1)

while (hour + offset) < now:
  starttime = hour.strftime("%H%M")
  date = hour.strftime("%Y%m%d")
  endtime = (hour + offset - datetime.timedelta(minutes=1)).strftime("%H%M")
  rawFile = rawFiles[hour.date()]
  data = subprocess.Popen(['blitzortung-data','-i', rawFile, '-s', starttime, '-e', endtime], stdout=subprocess.PIPE)

  (output, error) = data.communicate()

  # count the number of samples
  counter = 0
  ampsum = 0.0
  for line in output.splitlines():
    fields = whitespace.split(line)
    ampsum += float(fields[7])

    counter += 1


  time = hour + offset / 2
  
  if counter > 0:
    avgamp = ampsum/counter
  else:
    avgamp = '?'
  print time, counter, avgamp

  hour += offset
