#!/usr/bin/python

import os, sys
import subprocess

import datetime

import numpy

name = ""
now = datetime.datetime.utcnow()

hour = now.replace(minute=0, second=0, microsecond=0)


print hour,now

hour -= datetime.timedelta(days=1)

print hour,now

offset = datetime.timedelta(minutes=15)
while hour < now:
  starttime = hour.strftime("%H%M")
  date = hour.strftime("%Y%m%d")
  endtime = (hour + offset - datetime.timedelta(minutes=1)).strftime("%H%M")
  data = subprocess.Popen(['blitzortung-data','-i','/var/cache/blitzortung/raw/%s_%s.bor' %(name, date), '-s', starttime, '-e', endtime], stdout=subprocess.PIPE)

  (output, error) = data.communicate()

  counter = 0
  for line in output.splitlines():
    counter += 1
  print starttime, endtime, counter

  hour += offset
