#!/bin/bash

TARGETDIR=$1

if [ x$TARGETDIR == x ] ; then
  TARGETDIR="."
fi

TMPDATA=$(mktemp $(basename $0).XXXXXX)

blitzortung-statistics > $TMPDATA

gnuplot <<***
set term png
set output "$TARGETDIR/timecount.png"
set xdata time
set timefmt "%Y-%m-%d %H:%M:%S"
set xlabel "UTC time"
set ylabel "# of events"
set boxwidth 15*60
set log y
set yr [0.75:*]
set grid
set format x "%H:%M"
plot "$TMPDATA" u 1:3 not w boxes fs solid 0.5
***

gnuplot <<***
set term png
set output "$TARGETDIR/timeamp.png"
set xdata time
set timefmt "%Y-%m-%d %H:%M:%S"
set xlabel "UTC time"
set ylabel "average amplitude"
set boxwidth 15*60
set grid
set format x "%H:%M"
plot "$TMPDATA" u 1:4 not w boxes fs solid 0.5
***

rm -rf $TMPDATA
