#!/bin/bash

TARGETDIR=$1
RAWPATH=$2

NICE="nice -n 19"

PICXSIZE="480"
PICYSIZE="320"

if [ x$TARGETDIR == x ] ; then
  TARGETDIR="."
fi
if [ x$RAWPATH == x ]; then
  RAWPATH="/var/cache/blitzortung/raw"
fi

TMPDATA=$(mktemp /tmp/$(basename $0).XXXXXX)
STARTTIME=$(date +"%Y-%m-%d %H:%M:00" -d -1day)
ENDTIME=$(date +"%Y-%m-%d %H:%M:00")

$NICE blitzortung-statistics --mode=histogram --time-delta=15 --data-path=$RAWPATH > $TMPDATA

$NICE gnuplot <<***
set term png size $PICXSIZE,$PICYSIZE
set output "$TARGETDIR/timecount.png"
set xdata time
set timefmt "%Y-%m-%d %H:%M:%S"
set xlabel "UTC time"
set ylabel "# of events"
set boxwidth 15*60
set log y
set xr ["$STARTTIME":"$ENDTIME"]
set yr [0.75:*]
set grid
set format x "%H:%M"
plot 1 lt -2 not, "$TMPDATA" u 1:3 not w boxes lt 1 fs solid 0.5
***

$NICE gnuplot <<***
set term png size $PICXSIZE,$PICYSIZE
set output "$TARGETDIR/timeamp.png"
set xdata time
set timefmt "%Y-%m-%d %H:%M:%S"
set xlabel "UTC time"
set ylabel "average amplitude"
set boxwidth 15*60
set grid
set xr ["$STARTTIME":"$ENDTIME"]
set yr [0:*]
set format x "%H:%M"
set pointsize 0.8
plot 0.2 lt -2 not, "$TMPDATA" u 1:4 not w p 1 13
***

$NICE blitzortung-statistics --mode=data --time-delta=120 --data-path=$RAWPATH > $TMPDATA

$NICE gnuplot <<***
set term png size $PICYSIZE,$PICYSIZE
set output "$TARGETDIR/xyamp.png"
set size square
set title "last 2 hours"
set xlabel "x amplitude"
set ylabel "y amplitude"
set xr [-1.0:1.0]
set yr [-1.0:1.0]
set grid
plot "$TMPDATA" u 8:9 not
***

$NICE blitzortung-statistics --mode=strokes --time-delta=5 --data-path=$RAWPATH > $TMPDATA
STARTTIME=$(date +"%Y-%m-%d %H:%M:00" -d -115minutes)

$NICE gnuplot <<***
set term png size $PICXSIZE,$PICYSIZE
set output "$TARGETDIR/strokes.png"
set xdata time
set timefmt "%Y-%m-%d %H:%M:%S"
set xlabel "UTC time"
set ylabel "# of strokes"
set boxwidth 5*60
set log y
set xr ["$STARTTIME":"$ENDTIME"]
set yr [0.75:*]
set grid
set format x "%H:%M"
plot 1 lt -2 not, "$TMPDATA" u 1:3 ti "total" w boxes lt 1 fs solid 0.5, "" u 1:4 ti "sensor participated" w boxes lt 3 fs solid 0.5
***


rm -rf $TMPDATA
